export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
  displayOrder: number;
}

export interface SeedBrand {
  name: string;
  slug: string;
  description: string;
  country: string;
  displayOrder: number;
}

export interface SeedProduct {
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  brandSlug: string;
  shortDescription: string;
  description: string;
  ingredients: string;
  benefits: string[];
  usageInstructions: string;
  volume: string;
  skinTypes: string[];
  price: number;
  salePrice: number | null;
  stockOnHand: number;
  stockReserved: number;
  soldCount: number;
  ratingAverage: number;
  ratingCount: number;
  isActive: boolean;
  colors: [string, string];
}

export const seedCategories: SeedCategory[] = [
  { name: 'Sữa rửa mặt', slug: 'sua-rua-mat', description: 'Làm sạch dịu nhẹ, cân bằng độ ẩm cho da mỗi ngày.', displayOrder: 1 },
  { name: 'Toner & Nước cân bằng', slug: 'toner', description: 'Cân bằng pH và cấp ẩm tức thì sau bước làm sạch.', displayOrder: 2 },
  { name: 'Serum & Tinh chất', slug: 'serum', description: 'Dưỡng chất đậm đặc cho từng vấn đề da cụ thể.', displayOrder: 3 },
  { name: 'Kem dưỡng ẩm', slug: 'kem-duong-am', description: 'Khóa ẩm, phục hồi hàng rào bảo vệ da.', displayOrder: 4 },
  { name: 'Chống nắng', slug: 'chong-nang', description: 'Bảo vệ da khỏi tia UV và ánh sáng xanh.', displayOrder: 5 },
  { name: 'Mặt nạ & Tẩy tế bào chết', slug: 'mat-na-tay-te-bao-chet', description: 'Chăm sóc chuyên sâu 1-2 lần mỗi tuần.', displayOrder: 6 },
];

export const seedBrands: SeedBrand[] = [
  { name: 'La Roche-Posay', slug: 'la-roche-posay', description: 'Dược mỹ phẩm Pháp dành cho da nhạy cảm.', country: 'Pháp', displayOrder: 1 },
  { name: 'CeraVe', slug: 'cerave', description: 'Công thức ceramide phục hồi hàng rào da.', country: 'Mỹ', displayOrder: 2 },
  { name: 'Some By Mi', slug: 'some-by-mi', description: 'Thương hiệu Hàn Quốc nổi tiếng với dòng AHA-BHA-PHA.', country: 'Hàn Quốc', displayOrder: 3 },
  { name: 'Anessa', slug: 'anessa', description: 'Chống nắng Nhật Bản với khả năng kháng nước cao.', country: 'Nhật Bản', displayOrder: 4 },
  { name: 'The Ordinary', slug: 'the-ordinary', description: 'Hoạt chất đơn giản, nồng độ minh bạch.', country: 'Canada', displayOrder: 5 },
  { name: 'Cocoon', slug: 'cocoon', description: 'Mỹ phẩm thuần chay Việt Nam từ nguyên liệu bản địa.', country: 'Việt Nam', displayOrder: 6 },
];

export const seedProducts: SeedProduct[] = [
  {
    name: 'Sữa rửa mặt La Roche-Posay Effaclar Purifying Foaming Gel',
    slug: 'sua-rua-mat-la-roche-posay-effaclar-gel',
    sku: 'LRP-EFC-400',
    categorySlug: 'sua-rua-mat',
    brandSlug: 'la-roche-posay',
    shortDescription: 'Gel rửa mặt tạo bọt cho da dầu mụn, làm sạch bã nhờn mà không gây khô căng.',
    description:
      'Effaclar Purifying Foaming Gel làm sạch sâu bụi bẩn và dầu thừa trên da dầu, da dễ nổi mụn. Công thức chứa nước khoáng La Roche-Posay giúp làm dịu da, không chứa xà phòng, không cồn và không paraben.',
    ingredients: 'Aqua, Sodium Cocoamphoacetate, Coco-Betaine, Glycerin, Zinc PCA, Sodium Chloride, Citric Acid.',
    benefits: ['Làm sạch sâu bã nhờn', 'Không gây khô căng', 'Phù hợp da mụn nhạy cảm'],
    usageInstructions: 'Làm ướt mặt, lấy một lượng vừa đủ tạo bọt rồi massage nhẹ nhàng, rửa lại bằng nước sạch. Dùng 2 lần/ngày.',
    volume: '400ml',
    skinTypes: ['Da dầu', 'Da mụn', 'Da hỗn hợp'],
    price: 495000,
    salePrice: 429000,
    stockOnHand: 48,
    stockReserved: 3,
    soldCount: 320,
    ratingAverage: 4.7,
    ratingCount: 128,
    isActive: true,
    colors: ['#1f6feb', '#8fd3ff'],
  },
  {
    name: 'Sữa rửa mặt CeraVe Hydrating Cleanser',
    slug: 'sua-rua-mat-cerave-hydrating-cleanser',
    sku: 'CRV-HYD-473',
    categorySlug: 'sua-rua-mat',
    brandSlug: 'cerave',
    shortDescription: 'Sữa rửa mặt dạng kem cấp ẩm với 3 ceramide thiết yếu và hyaluronic acid.',
    description:
      'CeraVe Hydrating Cleanser làm sạch nhẹ nhàng mà vẫn giữ lại độ ẩm tự nhiên của da. Công nghệ MVE giải phóng dưỡng chất từ từ giúp da duy trì độ ẩm suốt cả ngày.',
    ingredients: 'Aqua, Glycerin, Cetearyl Alcohol, Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid, Cholesterol.',
    benefits: ['Cấp ẩm khi làm sạch', 'Phục hồi hàng rào bảo vệ da', 'Không hương liệu'],
    usageInstructions: 'Thoa lên da mặt ướt, massage nhẹ theo vòng tròn và rửa sạch. Dùng sáng và tối.',
    volume: '473ml',
    skinTypes: ['Da khô', 'Da thường', 'Da nhạy cảm'],
    price: 385000,
    salePrice: null,
    stockOnHand: 62,
    stockReserved: 0,
    soldCount: 410,
    ratingAverage: 4.8,
    ratingCount: 204,
    isActive: true,
    colors: ['#0b5ed7', '#cfe2ff'],
  },
  {
    name: 'Sữa rửa mặt Cocoon Bí Đao',
    slug: 'sua-rua-mat-cocoon-bi-dao',
    sku: 'CCN-BID-140',
    categorySlug: 'sua-rua-mat',
    brandSlug: 'cocoon',
    shortDescription: 'Gel rửa mặt thuần chay từ bí đao, hỗ trợ giảm dầu và mụn ẩn.',
    description:
      'Chiết xuất bí đao kết hợp tràm trà giúp làm sạch dịu nhẹ, kiềm dầu và hỗ trợ giảm mụn. Sản phẩm thuần chay, không thử nghiệm trên động vật.',
    ingredients: 'Aqua, Benincasa Hispida Fruit Extract, Melaleuca Alternifolia Leaf Oil, Glycerin, Panthenol.',
    benefits: ['Kiềm dầu tự nhiên', 'Hỗ trợ giảm mụn ẩn', 'Thuần chay 100%'],
    usageInstructions: 'Lấy 1-2 giọt, tạo bọt với nước rồi massage nhẹ nhàng lên da, rửa lại với nước.',
    volume: '140ml',
    skinTypes: ['Da dầu', 'Da mụn'],
    price: 185000,
    salePrice: 159000,
    stockOnHand: 4,
    stockReserved: 0,
    soldCount: 275,
    ratingAverage: 4.5,
    ratingCount: 96,
    isActive: true,
    colors: ['#0f9d58', '#c9f7d4'],
  },
  {
    name: 'Nước hoa hồng Some By Mi AHA-BHA-PHA 30 Days Miracle Toner',
    slug: 'toner-some-by-mi-aha-bha-pha-30-days',
    sku: 'SBM-TNR-150',
    categorySlug: 'toner',
    brandSlug: 'some-by-mi',
    shortDescription: 'Toner tẩy tế bào chết hóa học nhẹ dịu, làm sạch lỗ chân lông và làm sáng da.',
    description:
      'Bộ ba AHA-BHA-PHA kết hợp chiết xuất tràm trà giúp loại bỏ tế bào chết, thông thoáng lỗ chân lông và cải thiện kết cấu da sau 30 ngày sử dụng.',
    ingredients: 'Aqua, Melaleuca Alternifolia Leaf Water, Niacinamide, Lactobionic Acid, Salicylic Acid, Glycolic Acid.',
    benefits: ['Làm sạch lỗ chân lông', 'Giảm mụn đầu đen', 'Làm đều màu da'],
    usageInstructions: 'Sau khi rửa mặt, thấm toner ra bông tẩy trang và lau nhẹ toàn mặt. Dùng 1-2 lần/ngày.',
    volume: '150ml',
    skinTypes: ['Da dầu', 'Da mụn', 'Da hỗn hợp'],
    price: 350000,
    salePrice: 299000,
    stockOnHand: 35,
    stockReserved: 5,
    soldCount: 510,
    ratingAverage: 4.6,
    ratingCount: 312,
    isActive: true,
    colors: ['#6f42c1', '#e0d4ff'],
  },
  {
    name: 'Nước cân bằng Cocoon Rau Má',
    slug: 'toner-cocoon-rau-ma',
    sku: 'CCN-RMA-310',
    categorySlug: 'toner',
    brandSlug: 'cocoon',
    shortDescription: 'Toner rau má làm dịu da kích ứng và cấp ẩm nhẹ nhàng.',
    description:
      'Chiết xuất rau má Việt Nam giàu madecassoside giúp làm dịu da đỏ, kích ứng sau mụn và củng cố hàng rào bảo vệ da.',
    ingredients: 'Aqua, Centella Asiatica Extract, Glycerin, Panthenol, Allantoin, Sodium Hyaluronate.',
    benefits: ['Làm dịu da kích ứng', 'Cấp ẩm tức thì', 'Không cồn khô'],
    usageInstructions: 'Thấm ra bông hoặc vỗ trực tiếp lên da sau bước rửa mặt.',
    volume: '310ml',
    skinTypes: ['Da nhạy cảm', 'Da thường', 'Da khô'],
    price: 225000,
    salePrice: null,
    stockOnHand: 40,
    stockReserved: 0,
    soldCount: 180,
    ratingAverage: 4.4,
    ratingCount: 74,
    isActive: true,
    colors: ['#2e7d32', '#d7f2cf'],
  },
  {
    name: 'Tinh chất The Ordinary Niacinamide 10% + Zinc 1%',
    slug: 'serum-the-ordinary-niacinamide-10-zinc-1',
    sku: 'TOR-NIA-030',
    categorySlug: 'serum',
    brandSlug: 'the-ordinary',
    shortDescription: 'Serum kiểm soát dầu, mờ thâm mụn và se khít lỗ chân lông.',
    description:
      'Niacinamide 10% kết hợp kẽm PCA 1% giúp giảm tiết bã nhờn, làm mờ vết thâm sau mụn và cải thiện bề mặt da xỉn màu.',
    ingredients: 'Aqua, Niacinamide, Pentylene Glycol, Zinc PCA, Tamarindus Indica Seed Gum, Xanthan Gum.',
    benefits: ['Giảm dầu thừa', 'Mờ thâm sau mụn', 'Se khít lỗ chân lông'],
    usageInstructions: 'Dùng vài giọt lên da sạch buổi sáng và tối trước kem dưỡng. Tránh dùng chung với vitamin C thuần.',
    volume: '30ml',
    skinTypes: ['Da dầu', 'Da mụn', 'Da hỗn hợp'],
    price: 290000,
    salePrice: 239000,
    stockOnHand: 70,
    stockReserved: 8,
    soldCount: 640,
    ratingAverage: 4.5,
    ratingCount: 389,
    isActive: true,
    colors: ['#212529', '#adb5bd'],
  },
  {
    name: 'Serum The Ordinary Hyaluronic Acid 2% + B5',
    slug: 'serum-the-ordinary-hyaluronic-acid-2-b5',
    sku: 'TOR-HA2-030',
    categorySlug: 'serum',
    brandSlug: 'the-ordinary',
    shortDescription: 'Cấp nước đa tầng với ba phân tử hyaluronic acid và vitamin B5.',
    description:
      'Công thức hyaluronic acid đa trọng lượng phân tử giúp cấp nước ở nhiều tầng da, kết hợp B5 hỗ trợ phục hồi bề mặt da.',
    ingredients: 'Aqua, Sodium Hyaluronate, Panthenol, Ahnfeltia Concinna Extract, Glycerin, Pentylene Glycol.',
    benefits: ['Cấp nước đa tầng', 'Da căng mọng', 'Kết cấu nhẹ, thấm nhanh'],
    usageInstructions: 'Thoa lên da ẩm trước kem dưỡng, sáng và tối.',
    volume: '30ml',
    skinTypes: ['Mọi loại da'],
    price: 260000,
    salePrice: null,
    stockOnHand: 55,
    stockReserved: 0,
    soldCount: 298,
    ratingAverage: 4.3,
    ratingCount: 151,
    isActive: true,
    colors: ['#343a40', '#dee2e6'],
  },
  {
    name: 'Serum Some By Mi Snail Truecica Miracle Repair',
    slug: 'serum-some-by-mi-snail-truecica',
    sku: 'SBM-SNL-050',
    categorySlug: 'serum',
    brandSlug: 'some-by-mi',
    shortDescription: 'Tinh chất ốc sên phục hồi da tổn thương và làm mờ sẹo thâm.',
    description:
      'Kết hợp 80% dịch nhầy ốc sên đen và Truecica giúp tái tạo da sau mụn, làm mờ sẹo thâm và củng cố hàng rào bảo vệ da.',
    ingredients: 'Snail Secretion Filtrate, Centella Asiatica Extract, Niacinamide, Madecassoside, Panthenol.',
    benefits: ['Phục hồi da sau mụn', 'Làm mờ sẹo thâm', 'Tăng độ đàn hồi'],
    usageInstructions: 'Dùng 2-3 giọt sau bước toner, vỗ nhẹ cho thấm.',
    volume: '50ml',
    skinTypes: ['Da mụn', 'Da nhạy cảm', 'Da thường'],
    price: 520000,
    salePrice: 455000,
    stockOnHand: 0,
    stockReserved: 0,
    soldCount: 225,
    ratingAverage: 4.6,
    ratingCount: 118,
    isActive: true,
    colors: ['#495057', '#ced4da'],
  },
  {
    name: 'Kem dưỡng ẩm CeraVe Moisturising Cream',
    slug: 'kem-duong-am-cerave-moisturising-cream',
    sku: 'CRV-MOI-454',
    categorySlug: 'kem-duong-am',
    brandSlug: 'cerave',
    shortDescription: 'Kem dưỡng đậm đặc cho da khô đến rất khô, giữ ẩm đến 24 giờ.',
    description:
      'Công thức ba ceramide thiết yếu cùng hyaluronic acid giúp phục hồi hàng rào bảo vệ da và duy trì độ ẩm lâu dài cho cả mặt và toàn thân.',
    ingredients: 'Aqua, Glycerin, Cetearyl Alcohol, Ceramide NP, Ceramide AP, Ceramide EOP, Hyaluronic Acid, Petrolatum.',
    benefits: ['Dưỡng ẩm 24 giờ', 'Không gây bít tắc lỗ chân lông', 'Dùng được cho da nhạy cảm'],
    usageInstructions: 'Thoa đều lên da mặt và cơ thể, dùng sáng và tối hoặc khi da khô.',
    volume: '454g',
    skinTypes: ['Da khô', 'Da rất khô', 'Da nhạy cảm'],
    price: 520000,
    salePrice: 469000,
    stockOnHand: 30,
    stockReserved: 2,
    soldCount: 355,
    ratingAverage: 4.8,
    ratingCount: 240,
    isActive: true,
    colors: ['#0d6efd', '#e7f1ff'],
  },
  {
    name: 'Kem dưỡng La Roche-Posay Cicaplast Baume B5+',
    slug: 'kem-duong-la-roche-posay-cicaplast-baume-b5',
    sku: 'LRP-CIC-040',
    categorySlug: 'kem-duong-am',
    brandSlug: 'la-roche-posay',
    shortDescription: 'Kem phục hồi đa năng làm dịu da kích ứng, khô ráp và bong tróc.',
    description:
      'Cicaplast Baume B5+ chứa panthenol 5%, madecassoside và Tribioma giúp làm dịu tức thì, phục hồi vùng da tổn thương do treatment hoặc thời tiết.',
    ingredients: 'Aqua, Glycerin, Panthenol, Madecassoside, Zinc Gluconate, Shea Butter.',
    benefits: ['Làm dịu tức thì', 'Phục hồi da tổn thương', 'Dùng được cho trẻ nhỏ'],
    usageInstructions: 'Thoa lớp mỏng lên vùng da cần phục hồi, 1-2 lần/ngày.',
    volume: '40ml',
    skinTypes: ['Da nhạy cảm', 'Da khô', 'Da kích ứng'],
    price: 390000,
    salePrice: null,
    stockOnHand: 3,
    stockReserved: 0,
    soldCount: 198,
    ratingAverage: 4.9,
    ratingCount: 143,
    isActive: true,
    colors: ['#1565c0', '#bbdefb'],
  },
  {
    name: 'Kem chống nắng Anessa Perfect UV Sunscreen Skincare Milk SPF50+/PA++++',
    slug: 'kem-chong-nang-anessa-perfect-uv-milk',
    sku: 'ANS-UVM-060',
    categorySlug: 'chong-nang',
    brandSlug: 'anessa',
    shortDescription: 'Sữa chống nắng kháng nước, càng tiếp xúc nước và mồ hôi càng bảo vệ tốt hơn.',
    description:
      'Công nghệ Aqua Booster EX giúp lớp màng chống nắng bền vững khi gặp nước và mồ hôi. 50% thành phần dưỡng da giúp da không bị khô khi dùng hằng ngày.',
    ingredients: 'Water, Alcohol, Zinc Oxide, Ethylhexyl Methoxycinnamate, Hyaluronic Acid, Collagen, Vitamin E.',
    benefits: ['SPF50+ PA++++', 'Kháng nước vượt trội', 'Không gây bết dính'],
    usageInstructions: 'Lắc đều trước khi dùng, thoa lượng vừa đủ lên mặt và cổ 15 phút trước khi ra nắng. Thoa lại sau mỗi 2-3 giờ.',
    volume: '60ml',
    skinTypes: ['Mọi loại da'],
    price: 690000,
    salePrice: 615000,
    stockOnHand: 26,
    stockReserved: 4,
    soldCount: 470,
    ratingAverage: 4.7,
    ratingCount: 265,
    isActive: true,
    colors: ['#f59f00', '#ffe8b3'],
  },
  {
    name: 'Kem chống nắng La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF50+',
    slug: 'kem-chong-nang-la-roche-posay-anthelios-uvmune-400',
    sku: 'LRP-ANT-050',
    categorySlug: 'chong-nang',
    brandSlug: 'la-roche-posay',
    shortDescription: 'Fluid chống nắng không màu, không nhờn rít, bảo vệ cả tia UVA dài.',
    description:
      'Công nghệ Mexoryl 400 bảo vệ da trước tia UVA dài gây lão hóa và tăng sắc tố. Kết cấu fluid siêu nhẹ, tiệp màu da, phù hợp dùng dưới lớp trang điểm.',
    ingredients: 'Aqua, Mexoryl 400, Avobenzone, Glycerin, Tocopherol, Silica.',
    benefits: ['Bảo vệ UVA dài', 'Không để lại vệt trắng', 'Phù hợp da nhạy cảm'],
    usageInstructions: 'Thoa đều lên mặt vào buổi sáng, bước cuối cùng của chu trình dưỡng da.',
    volume: '50ml',
    skinTypes: ['Da nhạy cảm', 'Da dầu', 'Da hỗn hợp'],
    price: 545000,
    salePrice: null,
    stockOnHand: 44,
    stockReserved: 0,
    soldCount: 386,
    ratingAverage: 4.8,
    ratingCount: 210,
    isActive: true,
    colors: ['#1d4ed8', '#dbeafe'],
  },
  {
    name: 'Mặt nạ đất sét Some By Mi Yuja Niacin Brightening Mask',
    slug: 'mat-na-some-by-mi-yuja-niacin',
    sku: 'SBM-YUJ-100',
    categorySlug: 'mat-na-tay-te-bao-chet',
    brandSlug: 'some-by-mi',
    shortDescription: 'Mặt nạ đất sét thanh lọc da và làm sáng với chiết xuất thanh yên.',
    description:
      'Chiết xuất Yuja giàu vitamin C kết hợp niacinamide giúp làm sáng da xỉn màu, hút sạch bã nhờn và bụi bẩn trong lỗ chân lông.',
    ingredients: 'Kaolin, Citrus Junos Fruit Extract, Niacinamide, Bentonite, Glycerin, Panthenol.',
    benefits: ['Làm sáng da xỉn màu', 'Thanh lọc lỗ chân lông', 'Không làm khô da'],
    usageInstructions: 'Thoa một lớp mỏng lên da sạch, để 10-15 phút rồi rửa sạch. Dùng 1-2 lần/tuần.',
    volume: '100g',
    skinTypes: ['Da dầu', 'Da hỗn hợp', 'Da xỉn màu'],
    price: 340000,
    salePrice: 289000,
    stockOnHand: 21,
    stockReserved: 1,
    soldCount: 162,
    ratingAverage: 4.4,
    ratingCount: 88,
    isActive: true,
    colors: ['#f08c00', '#ffe9b8'],
  },
  {
    name: 'Tẩy tế bào chết Cocoon Cà Phê Đắk Lắk',
    slug: 'tay-te-bao-chet-cocoon-ca-phe-dak-lak',
    sku: 'CCN-CFE-200',
    categorySlug: 'mat-na-tay-te-bao-chet',
    brandSlug: 'cocoon',
    shortDescription: 'Tẩy da chết cơ học từ bã cà phê Đắk Lắk, làm mềm mịn da toàn thân.',
    description:
      'Hạt cà phê xay mịn kết hợp bơ ca cao giúp loại bỏ tế bào chết, kích thích tuần hoàn và để lại làn da mềm mịn, thơm nhẹ.',
    ingredients: 'Coffea Arabica Seed Powder, Theobroma Cacao Seed Butter, Glycerin, Cocos Nucifera Oil.',
    benefits: ['Làm mềm mịn da', 'Nguyên liệu Việt Nam', 'Thuần chay'],
    usageInstructions: 'Thoa lên da ẩm, massage tròn 2-3 phút rồi rửa sạch. Dùng 2 lần/tuần.',
    volume: '200ml',
    skinTypes: ['Mọi loại da'],
    price: 145000,
    salePrice: null,
    stockOnHand: 58,
    stockReserved: 0,
    soldCount: 210,
    ratingAverage: 4.2,
    ratingCount: 64,
    isActive: true,
    colors: ['#6f4e37', '#e5d3c0'],
  },
  {
    name: 'Serum Cocoon Bí Đao Giảm Mụn',
    slug: 'serum-cocoon-bi-dao-giam-mun',
    sku: 'CCN-SBD-070',
    categorySlug: 'serum',
    brandSlug: 'cocoon',
    shortDescription: 'Tinh chất bí đao hỗ trợ giảm mụn và làm dịu vùng da viêm.',
    description:
      'Bí đao kết hợp BHA tự nhiên từ vỏ liễu giúp giảm mụn viêm, làm dịu da và hạn chế mụn quay lại.',
    ingredients: 'Benincasa Hispida Fruit Extract, Salix Alba Bark Extract, Niacinamide, Panthenol, Allantoin.',
    benefits: ['Hỗ trợ giảm mụn viêm', 'Làm dịu da', 'Giá hợp lý'],
    usageInstructions: 'Dùng 3-4 giọt sau toner, tránh vùng mắt.',
    volume: '70ml',
    skinTypes: ['Da dầu', 'Da mụn'],
    price: 265000,
    salePrice: 225000,
    stockOnHand: 33,
    stockReserved: 0,
    soldCount: 143,
    ratingAverage: 4.1,
    ratingCount: 52,
    isActive: true,
    colors: ['#158f5b', '#c7f0dc'],
  },
  {
    name: 'Sữa rửa mặt Some By Mi (phiên bản ngừng kinh doanh)',
    slug: 'sua-rua-mat-some-by-mi-ngung-kinh-doanh',
    sku: 'SBM-OLD-100',
    categorySlug: 'sua-rua-mat',
    brandSlug: 'some-by-mi',
    shortDescription: 'Sản phẩm đã ngừng kinh doanh, dùng để kiểm thử trạng thái ẩn khỏi storefront.',
    description: 'Bản ghi không hoạt động phục vụ kiểm thử quy tắc FR-02.6: sản phẩm inactive không hiển thị ở storefront.',
    ingredients: 'Aqua, Glycerin.',
    benefits: [],
    usageInstructions: 'Không áp dụng.',
    volume: '100ml',
    skinTypes: [],
    price: 210000,
    salePrice: null,
    stockOnHand: 12,
    stockReserved: 0,
    soldCount: 5,
    ratingAverage: 3.8,
    ratingCount: 4,
    isActive: false,
    colors: ['#868e96', '#e9ecef'],
  },
];
